DROP TABLE IF EXISTS `CONTROL`;
CREATE TABLE `CONTROL` (
  `PROPERTY_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `PROPERTY_NAME` VARCHAR(64) DEFAULT 0 NOT NULL,
  `PROPERTY_VALUE` VARCHAR(255) DEFAULT 0 NOT NULL,
  `PROPERTY_ENABLED` INT(11) DEFAULT NULL,
  PRIMARY KEY (`PROPERTY_ID`)
);
INSERT INTO CONTROL (PROPERTY_ID,PROPERTY_NAME,PROPERTY_VALUE,PROPERTY_ENABLED) VALUES (1,'HISTORICAL_LOAD','1',1);
INSERT INTO CONTROL (PROPERTY_ID,PROPERTY_NAME,PROPERTY_VALUE,PROPERTY_ENABLED) VALUES (2,'ETL_EXTRACT_DATA_FROM','1970/01/01 00:00:00.000',1);
INSERT INTO CONTROL (PROPERTY_ID,PROPERTY_NAME,PROPERTY_VALUE,PROPERTY_ENABLED) VALUES (3,'ETL_EXTRACT_DATA_TO','1970/01/01 00:00:00.000',1);
INSERT INTO CONTROL (PROPERTY_ID,PROPERTY_NAME,PROPERTY_VALUE,PROPERTY_ENABLED) VALUES (4,'VERSION','0.1',1);
INSERT INTO CONTROL (PROPERTY_ID,PROPERTY_NAME,PROPERTY_VALUE,PROPERTY_ENABLED) VALUES (5,'ETL_RUNNING','0',1);
INSERT INTO CONTROL (PROPERTY_ID,PROPERTY_NAME,PROPERTY_VALUE,PROPERTY_ENABLED) VALUES (6,'BISERVER_RUNNING','0',1);
