DROP TABLE IF EXISTS `COUNTRY_CODES_MAPPING`;
CREATE TABLE COUNTRY_CODES_MAPPING
(
  COUNTRY VARCHAR(255)
, COUNTRY_CODE VARCHAR(12)
)
;CREATE INDEX IDX_COUNTRY_CODES_MAPPING_LKP ON COUNTRY_CODES_MAPPING(COUNTRY, COUNTRY_CODE)
;
