DROP TABLE IF EXISTS CUSTOM_FIELDS;
CREATE TABLE CUSTOM_FIELDS
(
  ID INT(11) NOT NULL AUTO_INCREMENT
, DB VARCHAR(256)
, ORIGINAL_TABLE VARCHAR(256)
, SUITECRM_SOURCE_TABLE_NAME VARCHAR(256)
, SUITECRM_SOURCE_COLUMN_NAME VARCHAR(256)
, TYPE_NAME VARCHAR(256)
, COLUMN_SIZE INT
, DECIMAL_DIGITS INT
, NUM_PREC_RADIX INT
, NULLABLE INT
, IS_NULLABLE VARCHAR(256)
, IS_AUTOINCREMENT VARCHAR(256)
, FIELD_ENABLED INT DEFAULT 0
, TARGET_TABLE VARCHAR(256)
, HAS_LENGTH CHAR(1)
, TARGET_FIELD_NAME VARCHAR(256)
, TARGET_TABLE_ID VARCHAR(256)
, FIELD_CREATED INT DEFAULT 0
, PRIMARY KEY (ID)
)
;CREATE INDEX IDX_CUSTOM_FIELDS_LKP ON CUSTOM_FIELDS(ID)
;
