DROP TABLE IF EXISTS D_ACTIVITIES;
CREATE TABLE D_ACTIVITIES (
    ACTIVITY_TK BIGINT NOT NULL,
    VERSION INT DEFAULT NULL,
    DATE_FROM DATETIME DEFAULT NULL,
    DATE_TO DATETIME DEFAULT NULL,
    ACTIVITY_ID VARCHAR(36) DEFAULT NULL,
    ACTIVITY_NAME VARCHAR(50) DEFAULT NULL,
    ACTIVITY_DESCRIPTION TEXT,
    ACTIVITY_PARENT_TYPE VARCHAR(255) DEFAULT NULL,
    ACTIVITY_TYPE VARCHAR(36) DEFAULT NULL,
    ACTIVITY_DELETED CHAR(1) DEFAULT NULL,
    PRIMARY KEY (`ACTIVITY_TK`),
    KEY `IDX_D_ACTIVITIES_LKP` (`ACTIVITY_ID`),
    KEY `IDX_D_ACTIVITIES_TK` (`ACTIVITY_TK`)
);