DROP TABLE IF EXISTS `D_CASES`;
CREATE TABLE `D_CASES` (
  `CASE_TK` BIGINT(20) NOT NULL,
  `VERSION` INT(11) DEFAULT NULL,
  `DATE_FROM` DATETIME DEFAULT NULL,
  `DATE_TO` DATETIME DEFAULT NULL,
  `CASE_ID` VARCHAR(36) DEFAULT NULL,
  `CASE_NAME` VARCHAR(255) DEFAULT NULL,
  `CASE_DESCRIPTION` TEXT,
  `CASE_DELETED` VARCHAR(3) DEFAULT NULL,
  `CASE_NUMBER` INT(11) DEFAULT NULL,
  `CASE_TYPE` VARCHAR(255) DEFAULT NULL,
  `CASE_STATUS` VARCHAR(100) DEFAULT NULL,
  `CASE_PRIORITY` VARCHAR(100) DEFAULT NULL,
  `CASE_RESOLUTION` TEXT,
  `CASE_STATE` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`CASE_TK`),
  KEY `IDX_D_CASES_LKP` (`CASE_ID`),
  KEY `IDX_D_CASES_TK` (`CASE_TK`)
);