DROP TABLE IF EXISTS `D_CONTRACTS`;
CREATE TABLE `D_CONTRACTS` (
  `CONTRACT_TK` bigint(20) NOT NULL,
  `VERSION` int(11) DEFAULT NULL,
  `DATE_FROM` datetime DEFAULT NULL,
  `DATE_TO` datetime DEFAULT NULL,
  `CONTRACT_ID` varchar(36) DEFAULT NULL,
  `CONTRACT_NAME` varchar(255) DEFAULT NULL,
  `CONTRACT_START_DATE` datetime DEFAULT NULL,
  `CONTRACT_END_DATE` datetime DEFAULT NULL,
  `CONTRACT_STATUS` varchar(100) DEFAULT NULL,
  `CONTRACT_CUSTOMER_SIGNED_DATE` datetime DEFAULT NULL,
  `CONTRACT_COMPANY_SIGNED_DATE` datetime DEFAULT NULL,
  `CONTRACT_TYPE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`CONTRACT_TK`),
  KEY `IDX_D_CONTRACTS_LKP` (`CONTRACT_ID`),
  KEY `IDX_D_CONTRACTS_TK` (`CONTRACT_TK`)
);
