DROP TABLE IF EXISTS `D_OPPORTUNITIES`;
CREATE TABLE `D_OPPORTUNITIES` (
  `OPPORTUNITY_TK` BIGINT(20) NOT NULL,
  `VERSION` INT(11) DEFAULT NULL,
  `DATE_FROM` DATETIME DEFAULT NULL,
  `DATE_TO` DATETIME DEFAULT NULL,
  `OPPORTUNITY_ID` VARCHAR(36) DEFAULT NULL,
  `OPPORTUNITY_NAME` VARCHAR(50) DEFAULT NULL,
  `OPPORTUNITY_CREATED_BY` VARCHAR(36) DEFAULT NULL,
  `OPPORTUNITY_DELETED` VARCHAR(3) DEFAULT NULL,
  `OPPORTUNITY_DESCRIPTION` TEXT,
  `OPPORTUNITY_TYPE` VARCHAR(255) DEFAULT NULL,
  `OPPORTUNITY_LEAD_SOURCE` VARCHAR(50) DEFAULT NULL,
  `OPPORTUNITY_NEXT_STEPS` VARCHAR(100) DEFAULT NULL,
  `OPPORTUNITY_SALES_STAGE` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`OPPORTUNITY_TK`),
  KEY `IDX_D_OPPORTUNITIES_LKP` (`OPPORTUNITY_ID`),
  KEY `IDX_D_OPPORTUNITIES_TK` (`OPPORTUNITY_TK`)
);