DROP TABLE IF EXISTS F_ACTIVITIES;
CREATE TABLE F_ACTIVITIES (
ACTIVITY_ID VARCHAR(36) DEFAULT NULL,
ACTIVITY_TK INT DEFAULT NULL,
ACTIVITY_DELETED CHAR(1) DEFAULT NULL,
ACTIVITY_DURATION INT DEFAULT NULL,
ASSIGNED_USER_TK INT DEFAULT NULL,
ACTIVITY_DATE_TK INT DEFAULT NULL,
ACTIVITY_PARENT_TK INT DEFAULT NULL
);

CREATE INDEX IDX_F_ACTIVITIES_LKP 
ON F_ACTIVITIES(ACTIVITY_ID);

CREATE INDEX IDX_ACTIVITY_TK
ON F_ACTIVITIES (ACTIVITY_TK);

CREATE INDEX IDX_ASSIGNED_USER_TK
ON F_ACTIVITIES (ASSIGNED_USER_TK);

CREATE INDEX IDX_ACTIVITY_DATE_TK
ON F_ACTIVITIES (ACTIVITY_DATE_TK);

CREATE INDEX IDX_ACTIVITY_PARENT_TK
ON F_ACTIVITIES (ACTIVITY_PARENT_TK);
