DROP TABLE IF EXISTS `F_CAMPAIGN_MANAGEMENT`;
CREATE TABLE `F_CAMPAIGN_MANAGEMENT` (
  `CAMPAIGN_ID` VARCHAR(36) NOT NULL,
  `CAMPAIGN_TK` INT(11) NOT NULL,
  `CAMPAIGN_START_DATE_TK` INT(11) NOT NULL DEFAULT 19000101,
  `CAMPAIGN_END_DATE_TK` INT(11) NOT NULL DEFAULT 19000101,
  `ASSIGNED_USER_TK` INT(11) NOT NULL,
  `CAMPAIGN_BUDGET`DECIMAL(26,6) NOT NULL DEFAULT 0.0,
  `CAMPAIGN_ACTUAL_COST` DECIMAL(26,6) NOT NULL DEFAULT 0.0,
  `CAMPAIGN_EXPECTED_COST` DECIMAL(26,6) NOT NULL DEFAULT 0.0,
  `CAMPAIGN_EXPECTED_REVENUE` DECIMAL(26,6) NOT NULL DEFAULT 0.0,
  `CAMPAIGN_DELETED` INT(1) NOT NULL,
  KEY `IDX_F_CAMPAIGN_MANAGEMENT_LKP` (`CAMPAIGN_ID`)
);
