DROP TABLE IF EXISTS `F_CONTRACT_MANAGEMENT`;

CREATE TABLE F_CONTRACT_MANAGEMENT (
   `CONTRACT_ID` VARCHAR(36) DEFAULT NULL,
   `CONTRACT_TK` INT(11) DEFAULT NULL,
   `OPPORTUNITY_TK` INT(11) DEFAULT NULL,
   `CONTACT_TK` INT(11) DEFAULT NULL,
   `ASSIGNED_USER_TK` INT(11) DEFAULT NULL,
   `CONTRACT_ACCOUNT_TK` INT(11) DEFAULT NULL,
   `CONTRACT_START_DATE_TK` INT(11) DEFAULT NULL,
   `CONTRACT_END_DATE_TK` INT(11) DEFAULT NULL,
   `CONTRACT_CREATED_TK` INT(11) DEFAULT NULL,
   KEY `IDX_F_CONTRACT_MANAGEMENT_LKP` (`CONTRACT_ID`)
);

CREATE INDEX IDX_CONTRACT_TK
ON F_CONTRACT_MANAGEMENT (CONTRACT_TK);

CREATE INDEX IDX_CONTACT_TK
ON F_CONTRACT_MANAGEMENT (CONTACT_TK);

CREATE INDEX IDX_CONTRACT_START_DATE_TK
ON F_CONTRACT_MANAGEMENT (CONTRACT_START_END_TK);

CREATE INDEX IDX_CONTRACT_START_END_TK
ON F_CONTRACT_MANAGEMENT (CONTRACT_END_END_TK);

CREATE INDEX IDX_CONTRACT_CREATED_TK
ON F_CONTRACT_MANAGEMENT (CONTRACT_CREATED_TK);

CREATE INDEX IDX_CONTACT_TK
ON F_CONTRACT_MANAGEMENT (CONTACT_TK);

CREATE INDEX IDX_OPPORTUNITY_TK
ON F_CONTRACT_MANAGEMENT (OPPORTUNITY_TK);

CREATE INDEX IDX_ASSIGNED_USER_TK
ON F_CONTRACT_MANAGEMENT (ASSIGNED_USER_TK);

