DROP TABLE IF EXISTS `F_INVOICE_MANAGEMENT`;
CREATE TABLE `F_INVOICE_MANAGEMENT` (
  `INVOICE_LINE_ID` VARCHAR(36) DEFAULT NULL,
  `INVOICE_LINE_QUANTITY` DECIMAL(18,4) DEFAULT NULL,
  `ASSIGNED_USER_TK` INT(11) DEFAULT NULL,
  `BILLING_ACCOUNT_TK` INT(11) DEFAULT NULL,
  `INVOICE_LINE_DISCOUNT_VALUE` DECIMAL(26,6) DEFAULT NULL,
  `INVOICE_LINE_DISCOUNT_AMOUNT` DECIMAL(26,6) DEFAULT NULL,
  `INVOICE_LINE_DISCOUNT_TYPE` VARCHAR(255) DEFAULT NULL,
  `INVOICE_LINE_VAT_VALUE` VARCHAR(100) DEFAULT NULL,
  `PRODUCT_TK` INT(11) DEFAULT NULL,
  `INVOICE_LINE_COST_PRICE_AMOUNT` DECIMAL(26,6) DEFAULT NULL,
  `INVOICE_LINE_LIST_PRICE_AMOUNT` DECIMAL(26,6) DEFAULT NULL,
  `INVOICE_LINE_UNIT_PRICE_AMOUNT` DECIMAL(26,6) DEFAULT NULL,
  `INVOICE_LINE_TOTAL_VAT_AMOUNT` DECIMAL(26,6) DEFAULT NULL,
  `INVOICE_LINE_TOTAL_AMOUNT` DECIMAL(26,6) DEFAULT NULL,
  `INVOICE_LINE_TOTAL_DISCOUNT_AMOUNT` DOUBLE DEFAULT NULL,
  `INVOICE_TK` INT(11) DEFAULT NULL,
  `INVOICE_DATE_TK` INT(11) DEFAULT NULL,
  `INVOICE_DUE_DATE_TK` INT(11) DEFAULT NULL,
  `INVOICE_DELETED` INT(1) DEFAULT NULL,
  `INVOICE_LINE_DELETED` INT(1) DEFAULT NULL,
  KEY `IDX_F_INVOICE_MANAGEMENT_LKP` (`INVOICE_LINE_ID`)
);