DROP TABLE IF EXISTS `F_LEAD_TRACKING`;
CREATE TABLE F_LEAD_TRACKING
(
  LEAD_ID VARCHAR(36)
, STATUS VARCHAR(255)
, STATUS_DATE DATETIME
, EVENT_COUNT INT
, EVENT_STATUS INT
, LEAD_TK INT
, OPPORTUNITY_TK INT
, ASSIGNED_USER_TK INT
, CAMPAIGN_TK INT
, EVENT_CREATED_TK INT
, EVENT_AGE DOUBLE
, EVENT_ORDER INT
)
;

CREATE INDEX IDX_F_LEAD_TRACKING_LKP
ON F_LEAD_TRACKING(LEAD_ID, STATUS, STATUS_DATE)
;
