DROP TABLE IF EXISTS `F_LEAD_MANAGEMENT`;
CREATE TABLE `F_LEAD_MANAGEMENT` (
  `LEAD_ID` VARCHAR(36) DEFAULT NULL,
  `LEAD_TK` INT(11) DEFAULT NULL,
  `OPPORTUNITY_TK` INT(11) DEFAULT NULL,
  `LEAD_CREATED_TK` INT(11) DEFAULT NULL,
  `LEAD_CONVERTED_TK` INT(11) DEFAULT NULL,
  `CAMPAIGN_TK` INT(11) DEFAULT NULL,
  `LEAD_MODIFIED_TK` INT(11) DEFAULT NULL,
  `ASSIGNED_USER_TK` INT(11) DEFAULT NULL,
  KEY `IDX_F_LEAD_MANAGEMENT_LKP` (`LEAD_ID`)
);

CREATE INDEX IDX_CAMPAIGN_TK
ON F_LEAD_MANAGEMENT (CAMPAIGN_TK);

CREATE INDEX IDX_LEAD_CONVERTED_TK
ON F_LEAD_MANAGEMENT (LEAD_CONVERTED_TK);

CREATE INDEX IDX_LEAD_CREATED_TK
ON F_LEAD_MANAGEMENT (LEAD_CREATED_TK);

CREATE INDEX IDX_LEAD_MODIFIED_TK
ON F_LEAD_MANAGEMENT (LEAD_MODIFIED_TK);

CREATE INDEX IDX_LEAD_TK
ON F_LEAD_MANAGEMENT (LEAD_TK);

CREATE INDEX IDX_OPPORTUNITY_TK
ON F_LEAD_MANAGEMENT (OPPORTUNITY_TK);

CREATE INDEX IDX_ASSIGNED_USER_TK
ON F_LEAD_MANAGEMENT (ASSIGNED_USER_TK);
