DROP TABLE IF EXISTS `F_OPPORTUNITY_TRACKING`;
CREATE TABLE F_OPPORTUNITY_TRACKING
(
  OPPORTUNITY_ID VARCHAR(36)
, STATUS VARCHAR(255)
, STATUS_DATE DATETIME
, EVENT_COUNT INT
, EVENT_STATUS INT
, OPPORTUNITY_TK INT
, ASSIGNED_USER_TK INT
, CAMPAIGN_TK INT
, EVENT_CREATED_TK INT
, ACCOUNT_TK INT
, EVENT_AGE DOUBLE
)
;
CREATE INDEX IDX_F_OPPORTUNITY_TRACKING_LKP 
ON F_OPPORTUNITY_TRACKING(OPPORTUNITY_ID, STATUS, STATUS_DATE)
;