CREATE TABLE F_SALES
(
  SALE_ID VARCHAR(36)
, INVOICE_TK INT
, PRODUCT_TK INT
, BILLING_ACCOUNT_TK INT
, ASSIGNED_USER_TK INT
, SALE_PAID_DATE_TK INT
, SALE_QUANTITY DECIMAL(18, 4)
, SALE_COST_PRICE_AMOUNT DECIMAL(26, 6)
, SALE_LIST_PRICE_AMOUNT DECIMAL(26, 6)
, SALE_DISCOUNT_TYPE VARCHAR(20)
, SALE_DISCOUNT_VALUE DECIMAL(26, 6)
, SALE_DISCOUNT_AMOUNT DECIMAL(26, 6)
, SALE_UNIT_PRICE_AMOUNT DECIMAL(26, 6)
, SALE_VAT_VALUE DOUBLE
, SALE_TOTAL_VAT_AMOUNT DECIMAL(26, 6)
, SALE_TOTAL_DISCOUNT_AMOUNT DOUBLE
, SALE_TOTAL_AMOUNT DECIMAL(26, 6)
)
;CREATE INDEX idx_F_SALES_lookup ON F_SALES(SALE_ID)
;
