DROP TABLE IF EXISTS `REPORT_PARAMETER_MAPPING`;
CREATE TABLE REPORT_PARAMETER_MAPPING
(
  REPORT VARCHAR(256)
, PARAMETER VARCHAR(256)
, PARAMETER_LABEL VARCHAR(256)
, DEFAULT_VALUE VARCHAR(256)
)
;
