DROP TABLE IF EXISTS `S_ACCOUNTS_CONTACTS`;
CREATE TABLE `S_ACCOUNTS_CONTACTS` (
  `id` VARCHAR(36) DEFAULT NULL,
  `contact_id` VARCHAR(36) DEFAULT NULL,
  `account_id` VARCHAR(36) DEFAULT NULL,
  `date_modified` DATETIME DEFAULT NULL,
  `deleted` CHAR(1) DEFAULT NULL
);