DROP TABLE IF EXISTS `S_CONTACTS`;
CREATE TABLE `S_CONTACTS` (
  `id` VARCHAR(36) DEFAULT NULL,
  `date_entered` DATETIME DEFAULT NULL,
  `date_modified` DATETIME DEFAULT NULL,
  `modified_user_id` VARCHAR(36) DEFAULT NULL,
  `created_by` VARCHAR(36) DEFAULT NULL,
  `description` TEXT,
  `deleted` CHAR(1) DEFAULT NULL,
  `assigned_user_id` VARCHAR(36) DEFAULT NULL,
  `salutation` VARCHAR(255) DEFAULT NULL,
  `first_name` VARCHAR(100) DEFAULT NULL,
  `last_name` VARCHAR(100) DEFAULT NULL,
  `title` VARCHAR(100) DEFAULT NULL,
  `photo` VARCHAR(255) DEFAULT NULL,
  `department` VARCHAR(255) DEFAULT NULL,
  `do_not_call` CHAR(1) DEFAULT NULL,
  `phone_home` VARCHAR(100) DEFAULT NULL,
  `phone_mobile` VARCHAR(100) DEFAULT NULL,
  `phone_work` VARCHAR(100) DEFAULT NULL,
  `phone_other` VARCHAR(100) DEFAULT NULL,
  `phone_fax` VARCHAR(100) DEFAULT NULL,
  `lawful_basis` TEXT,
  `date_reviewed` DATETIME DEFAULT NULL,
  `lawful_basis_source` VARCHAR(100) DEFAULT NULL,
  `primary_address_street` VARCHAR(150) DEFAULT NULL,
  `primary_address_city` VARCHAR(100) DEFAULT NULL,
  `primary_address_state` VARCHAR(100) DEFAULT NULL,
  `primary_address_postalcode` VARCHAR(20) DEFAULT NULL,
  `primary_address_country` VARCHAR(255) DEFAULT NULL,
  `alt_address_street` VARCHAR(150) DEFAULT NULL,
  `alt_address_city` VARCHAR(100) DEFAULT NULL,
  `alt_address_state` VARCHAR(100) DEFAULT NULL,
  `alt_address_postalcode` VARCHAR(20) DEFAULT NULL,
  `alt_address_country` VARCHAR(255) DEFAULT NULL,
  `assistant` VARCHAR(75) DEFAULT NULL,
  `assistant_phone` VARCHAR(100) DEFAULT NULL,
  `lead_source` VARCHAR(255) DEFAULT NULL,
  `reports_to_id` VARCHAR(36) DEFAULT NULL,
  `birthdate` DATETIME DEFAULT NULL,
  `campaign_id` VARCHAR(36) DEFAULT NULL,
  `joomla_account_id` VARCHAR(255) DEFAULT NULL,
  `portal_account_disabled` CHAR(1) DEFAULT NULL,
  `portal_user_type` VARCHAR(100) DEFAULT NULL
);