DROP TABLE IF EXISTS `S_LEADS`;
CREATE TABLE `S_LEADS` (
  `id` VARCHAR(36) DEFAULT NULL,
  `date_entered` DATETIME DEFAULT NULL,
  `date_modified` DATETIME DEFAULT NULL,
  `modified_user_id` VARCHAR(36) DEFAULT NULL,
  `created_by` VARCHAR(36) DEFAULT NULL,
  `description` TEXT,
  `deleted` CHAR(1) DEFAULT NULL,
  `assigned_user_id` VARCHAR(36) DEFAULT NULL,
  `salutation` VARCHAR(255) DEFAULT NULL,
  `first_name` VARCHAR(100) DEFAULT NULL,
  `last_name` VARCHAR(100) DEFAULT NULL,
  `title` VARCHAR(100) DEFAULT NULL,
  `photo` VARCHAR(255) DEFAULT NULL,
  `department` VARCHAR(100) DEFAULT NULL,
  `do_not_call` CHAR(1) DEFAULT NULL,
  `phone_home` VARCHAR(100) DEFAULT NULL,
  `phone_mobile` VARCHAR(100) DEFAULT NULL,
  `phone_work` VARCHAR(100) DEFAULT NULL,
  `phone_other` VARCHAR(100) DEFAULT NULL,
  `phone_fax` VARCHAR(100) DEFAULT NULL,
  `primary_address_street` VARCHAR(150) DEFAULT NULL,
  `primary_address_city` VARCHAR(100) DEFAULT NULL,
  `primary_address_state` VARCHAR(100) DEFAULT NULL,
  `primary_address_postalcode` VARCHAR(20) DEFAULT NULL,
  `primary_address_country` VARCHAR(255) DEFAULT NULL,
  `alt_address_street` VARCHAR(150) DEFAULT NULL,
  `alt_address_city` VARCHAR(100) DEFAULT NULL,
  `alt_address_state` VARCHAR(100) DEFAULT NULL,
  `alt_address_postalcode` VARCHAR(20) DEFAULT NULL,
  `alt_address_country` VARCHAR(255) DEFAULT NULL,
  `assistant` VARCHAR(75) DEFAULT NULL,
  `assistant_phone` VARCHAR(100) DEFAULT NULL,
  `converted` CHAR(1) DEFAULT NULL,
  `refered_by` VARCHAR(100) DEFAULT NULL,
  `lead_source` VARCHAR(100) DEFAULT NULL,
  `lead_source_description` TEXT,
  `status` VARCHAR(100) DEFAULT NULL,
  `status_description` TEXT,
  `reports_to_id` VARCHAR(36) DEFAULT NULL,
  `account_name` VARCHAR(255) DEFAULT NULL,
  `account_description` TEXT,
  `contact_id` VARCHAR(36) DEFAULT NULL,
  `account_id` VARCHAR(36) DEFAULT NULL,
  `opportunity_id` VARCHAR(36) DEFAULT NULL,
  `opportunity_name` VARCHAR(255) DEFAULT NULL,
  `opportunity_amount` VARCHAR(50) DEFAULT NULL,
  `campaign_id` VARCHAR(36) DEFAULT NULL,
  `birthdate` DATETIME DEFAULT NULL,
  `portal_name` VARCHAR(255) DEFAULT NULL,
  `portal_app` VARCHAR(255) DEFAULT NULL,
  `website` VARCHAR(255) DEFAULT NULL
);