DROP TABLE IF EXISTS `S_PRODUCT_QUOTES`;
CREATE TABLE `S_PRODUCT_QUOTES` (
  `id` VARCHAR(36) DEFAULT NULL,
  `name` TEXT,
  `date_entered` DATETIME DEFAULT NULL,
  `date_modified` DATETIME DEFAULT NULL,
  `modified_user_id` VARCHAR(36) DEFAULT NULL,
  `created_by` VARCHAR(36) DEFAULT NULL,
  `description` TEXT,
  `deleted` CHAR(1) DEFAULT NULL,
  `assigned_user_id` VARCHAR(36) DEFAULT NULL,
  `currency_id` VARCHAR(36) DEFAULT NULL,
  `part_number` VARCHAR(255) DEFAULT NULL,
  `item_description` TEXT,
  `number` INT(11) DEFAULT NULL,
  `product_qty` DECIMAL(18,4) DEFAULT NULL,
  `product_cost_price` DECIMAL(26,6) DEFAULT NULL,
  `product_cost_price_usdollar` DECIMAL(26,6) DEFAULT NULL,
  `product_list_price` DECIMAL(26,6) DEFAULT NULL,
  `product_list_price_usdollar` DECIMAL(26,6) DEFAULT NULL,
  `product_discount` DECIMAL(26,6) DEFAULT NULL,
  `product_discount_usdollar` DECIMAL(26,6) DEFAULT NULL,
  `product_discount_amount` DECIMAL(26,6) DEFAULT NULL,
  `product_discount_amount_usdollar` DECIMAL(26,6) DEFAULT NULL,
  `discount` VARCHAR(255) DEFAULT NULL,
  `product_unit_price` DECIMAL(26,6) DEFAULT NULL,
  `product_unit_price_usdollar` DECIMAL(26,6) DEFAULT NULL,
  `vat_amt` DECIMAL(26,6) DEFAULT NULL,
  `vat_amt_usdollar` DECIMAL(26,6) DEFAULT NULL,
  `product_total_price` DECIMAL(26,6) DEFAULT NULL,
  `product_total_price_usdollar` DECIMAL(26,6) DEFAULT NULL,
  `vat` VARCHAR(100) DEFAULT NULL,
  `parent_type` VARCHAR(100) DEFAULT NULL,
  `parent_id` VARCHAR(36) DEFAULT NULL,
  `product_id` VARCHAR(36) DEFAULT NULL,
  `group_id` VARCHAR(36) DEFAULT NULL
);