DROP TABLE IF EXISTS `S_PRODUCT_CATEGORIES`;
CREATE TABLE `S_PRODUCT_CATEGORIES` (
  `id` VARCHAR(36) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `date_entered` DATETIME DEFAULT NULL,
  `date_modified` DATETIME DEFAULT NULL,
  `modified_user_id` VARCHAR(36) DEFAULT NULL,
  `created_by` VARCHAR(36) DEFAULT NULL,
  `description` TEXT,
  `deleted` CHAR(1) DEFAULT NULL,
  `assigned_user_id` VARCHAR(36) DEFAULT NULL,
  `is_parent` CHAR(1) DEFAULT NULL,
  `parent_category_id` VARCHAR(36) DEFAULT NULL
);