INSERT INTO D_ACCOUNTS
(
	ACCOUNT_TK
	,VERSION
	,DATE_FROM
	,DATE_TO
	,ACCOUNT_ID
	,ACCOUNT_DELETED
	,ACCOUNT_NAME
	,ACCOUNT_DATE_CREATED
	,ACCOUNT_MODIFIED
	,ACCOUNT_CREATED_BY
	,ACCOUNT_DESCRIPTION
	,ACCOUNT_TYPE
	,ACCOUNT_INDUSTRY
	,ACCOUNT_BILLING_ADDRESS_CITY
	,ACCOUNT_BILLING_ADDRESS_COUNTRY
	,ACCOUNT_BILLING_ADDRESS_POSTCODE
	,ACCOUNT_BILLING_ADDRESS_STATE
	,ACCOUNT_BILLING_ADDRESS_STREET
	,ACCOUNT_SHIPPING_ADDRESS_CITY
	,ACCOUNT_SHIPPING_ADDRESS_COUNTRY
	,ACCOUNT_SHIPPING_ADDRESS_POSTCODE
	,ACCOUNT_SHIPPING_ADDRESS_STATE
	,ACCOUNT_SHIPPING_ADDRESS_STREET
)
VALUES (
	0
	,1
	,{ts '1900-01-01 00:00:00.'}
	,{ts '2200-01-01 00:00:00.'}
	,'N/A'
	,'No'
	,'Not Set'
	,{ts '1900-01-01 00:00:00.'}
	,{ts '1900-01-01 00:00:00.'}
	,'N/A'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
);
