INSERT INTO D_LEADS
(
	LEAD_TK
	,VERSION
	,DATE_FROM
	,DATE_TO
	,LEAD_ID
	,LEAD_DELETED
	,LEAD_DESCRIPTION
	,LEAD_SALUTATION
	,LEAD_TITLE
	,LEAD_SOURCE
	,LEAD_SOURCE_DESCRIPTION
	,LEAD_STATUS
	,LEAD_STATUS_DESCRIPTION
	,LEAD_ACCOUNT_NAME
	,LEAD_ACCOUNT_DESCRIPTION
	,LEAD_OPPORTUNITY_NAME
	,LEAD_OPPORTUNITY_AMOUNT
	,LEAD_WEBSITE
	,LEAD_FULL_NAME
	,LEAD_PRIMARY_ADDRESS_CITY
	,LEAD_PRIMARY_ADDRESS_COUNTRY
	,LEAD_PRIMARY_ADDRESS_STATE
	,LEAD_PRIMARY_ADDRESS_POSTCODE
	,LEAD_PRIMARY_ADDRESS_STREET
	,LEAD_CONVERTED
)
VALUES (
	0,
	1,
	{ts '1900-01-01 00:00:00.'}
	,{ts '2200-01-01 00:00:00.'}
	,'N/A'
	,'No'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
	,'Not Set'
);
