INSERT INTO D_OPPORTUNITIES
(
	OPPORTUNITY_TK
	,VERSION
	,DATE_FROM
	,DATE_TO
	,OPPORTUNITY_ID
	,OPPORTUNITY_DELETED
	,OPPORTUNITY_NAME
	,OPPORTUNITY_CREATED_BY
	,OPPORTUNITY_DESCRIPTION
	,OPPORTUNITY_TYPE
	,OPPORTUNITY_LEAD_SOURCE
	,OPPORTUNITY_NEXT_STEPS
	,OPPORTUNITY_SALES_STAGE
)
VALUES (
        0
        ,1
        ,{ts '1900-01-01 00:00:00.'}
        ,{ts '2200-01-01 00:00:00.'}
        ,'N/A'
	,'No'
        ,'Not Set'
        ,'Not Set'
        ,'Not Set'
        ,'Not Set'
        ,'Not Set'
        ,'Not Set'
        ,'Not Set'
);
