SELECT 
	DL.LEAD_FULL_NAME,
	DA.ACTIVITY_TYPE,
	COUNT(FA.ACTIVITY_TK),
	SUM(FA.ACTIVITY_DURATION)
FROM F_ACTIVITIES FA
INNER JOIN D_ACTIVITIES DA
ON FA.ACTIVITY_TK = DA.ACTIVITY_TK
INNER JOIN D_LEADS DL
ON FA.ACTIVITY_PARENT_TK = DL.LEAD_TK
WHERE DA.ACTIVITY_PARENT_TYPE = 'Leads'
GROUP BY 1,2

SELECT 
	DO.OPPORTUNITY_NAME,
	DA.ACTIVITY_TYPE,
	COUNT(FA.ACTIVITY_TK),
	SUM(FA.ACTIVITY_DURATION)
FROM F_ACTIVITIES FA
INNER JOIN D_ACTIVITIES DA
ON FA.ACTIVITY_TK = DA.ACTIVITY_TK
INNER JOIN D_OPPORTUNITIES DO
ON FA.ACTIVITY_PARENT_TK = DO.OPPORTUNITY_TK
WHERE DA.ACTIVITY_PARENT_TYPE = 'Opportunities'
GROUP BY 1,2
