select * from F_CASE_MANAGEMENT;

select * from D_CASES;


SELECT * 
FROM F_CASE_MANAGEMENT FCM
INNER JOIN D_CASES DC
	ON FCM.CASE_TK = DC.CASE_TK
INNER JOIN D_DATE CCRD
	ON FCM.CASE_CREATED_TK = CCRD.DATE_TK;
--INNER JOIN D_DATE CCLD
--	ON FCM.CASE_CLOSED_TK = CCLD.DATE_TK

-- Total Cases by Priority and Month

SELECT
	DC.CASE_PRIORITY
	,CCRD.`YYYY-MM` 
	,COUNT(*) AS TOTAL_CASES
FROM F_CASE_MANAGEMENT FCM
INNER JOIN D_CASES DC
	ON FCM.CASE_TK = DC.CASE_TK
INNER JOIN D_DATE CCRD
	ON FCM.CASE_CREATED_TK = CCRD.DATE_TK
GROUP BY 1,2

-- Total Cases Created by single Priority and Month

SELECT
	DC.CASE_PRIORITY
	,CCRD.`YYYY-MM` 
	,COUNT(*) AS TOTAL_CASES
FROM F_CASE_MANAGEMENT FCM
INNER JOIN D_CASES DC
	ON FCM.CASE_TK = DC.CASE_TK
INNER JOIN D_DATE CCRD
	ON FCM.CASE_CREATED_TK = CCRD.DATE_TK
WHERE DC.CASE_PRIORITY = 'P1'
GROUP BY 1,2






SELECT
	DC.CASE_PRIORITY
	,CCRD.`YYYY-MM` 
	,COUNT(*) AS TOTAL_CASES
FROM F_CASE_MANAGEMENT FCM
INNER JOIN D_CASES DC
	ON FCM.CASE_TK = DC.CASE_TK
INNER JOIN D_DATE CCRD
	ON FCM.CASE_CLOSED_TK = CCRD.DATE_TK
WHERE DC.CASE_PRIORITY = 'P1'
GROUP BY 1,2






-- Total Cases by single Priority

SELECT
	DC.CASE_PRIORITY
	,COUNT(*) AS TOTAL_CASES
FROM F_CASE_MANAGEMENT FCM
INNER JOIN D_CASES DC
	ON FCM.CASE_TK = DC.CASE_TK
WHERE DC.CASE_PRIORITY = 'P1'
GROUP BY 1;

-- Total Cases by Priority pivot with Month

SELECT
	CCRD.`YYYY-MM` 
	,SUM(IF(DC.CASE_PRIORITY = 'P1', 1, 0)) AS TOTAL_P1_CASES
	,SUM(IF(DC.CASE_PRIORITY = 'P2', 1, 0)) AS TOTAL_P2_CASES
	,SUM(IF(DC.CASE_PRIORITY = 'P3', 1, 0)) AS TOTAL_P3_CASES
	,COUNT(FCM.CASE_TK) AS TOTAL_CASES 
FROM F_CASE_MANAGEMENT FCM
INNER JOIN D_CASES DC
	ON FCM.CASE_TK = DC.CASE_TK
INNER JOIN D_DATE CCRD
	ON FCM.CASE_CREATED_TK = CCRD.DATE_TK
GROUP BY 1

-- Total Cases Percent by Priority pivot with Month

SELECT
	CCRD.`YYYY-MM` 
	,(SUM(IF(DC.CASE_PRIORITY = 'P1', 1, 0)) / COUNT(FCM.CASE_TK) ) * 100 AS TOTAL_P1_CASES
	,(SUM(IF(DC.CASE_PRIORITY = 'P2', 1, 0)) / COUNT(FCM.CASE_TK) ) * 100 AS TOTAL_P2_CASES
	,(SUM(IF(DC.CASE_PRIORITY = 'P3', 1, 0)) / COUNT(FCM.CASE_TK) ) * 100 AS TOTAL_P3_CASES
	,COUNT(FCM.CASE_TK) AS TOTAL_CASES 
FROM F_CASE_MANAGEMENT FCM
INNER JOIN D_CASES DC
	ON FCM.CASE_TK = DC.CASE_TK
INNER JOIN D_DATE CCRD
	ON FCM.CASE_CREATED_TK = CCRD.DATE_TK
GROUP BY 1

-- Total Cases by Status

SELECT 
	COUNT(FCM.CASE_ID) AS TOTAL_CASES
FROM F_CASE_MANAGEMENT FCM
INNER JOIN D_CASES DC
	ON FCM.CASE_TK = DC.CASE_TK;

SELECT 
	CONCAT(DU.USER_FIRST_NAME , ' ' , DU.USER_LAST_NAME) EMPLOYEE_FULL_NAME
	,(SUM(IF(DC.CASE_STATUS = 'New', 1, 0)) / COUNT(FCM.CASE_TK)) * 100 AS NEW_CASE_PERCENT
	,SUM(IF(DC.CASE_STATUS = 'New', 1, 0)) AS NEW_CASE_COUNT
	,SUM(IF(DC.CASE_STATUS = 'Assigned', 1, 0)) AS ASSIGNED_CASE_COUNT
	,SUM(IF(DC.CASE_STATUS = 'Pending Input', 1, 0)) AS PENDING_INPUT_CASE_COUNT
	,SUM(IF(DC.CASE_STATUS = 'Closed', 1, 0)) AS CLOSED_CASE_COUNT
	,SUM(IF(DC.CASE_STATUS = 'Rejected', 1, 0)) AS REJECTED_CASE_COUNT
	,SUM(IF(DC.CASE_STATUS = 'Duplicate', 1, 0)) AS DUPLICATE_CASE_COUNT
	,COUNT(FCM.CASE_TK) TOTAL_CASES
FROM F_CASE_MANAGEMENT AS FCM
INNER JOIN D_USERS AS DU 
	ON FCM.ASSIGNED_USER_TK = DU.USER_TK
INNER JOIN D_CASES AS DC 
	ON FCM.CASE_TK = DC.CASE_TK
INNER JOIN D_DATE DD
	ON FCM.CASE_CREATED_TK = DD.DATE_TK
GROUP BY DU.USER_TK;


SELECT 
    COUNT(IF(DD.`YYYYMM` = ${pDateFilter}, FLM.LEAD_TK, NULL)) AS CURRENT_NEW_LEADS
    ,COUNT(IF(DD.`YYYYMM` = ${pDateFilter} - 1, FLM.LEAD_TK, NULL)) AS PREVIOUS_NEW_LEADS
FROM F_LEAD_MANAGEMENT FLM
INNER JOIN D_LEADS DL
	ON FLM.LEAD_TK = DL.LEAD_TK
INNER JOIN D_CAMPAIGNS AS DC 
	ON FLM.CAMPAIGN_TK = DC.CAMPAIGN_TK
INNER JOIN D_DATE DD
	ON FLM.LEAD_MODIFIED_TK = DD.DATE_TK
WHERE DL.LEAD_STATUS = 'New'
--AND DD.`YYYYMM` IN (${pDateFilter},${pDateFilter} - 1)
--AND (DC.CAMPAIGN_TYPE IN (${pCampaignTypeFilter}) OR 'All Campaign Types' IN (${pCampaignTypeFilter}))
--AND (DC.CAMPAIGN_NAME IN (${pCampaignFilter}) OR 'All Campaigns' IN (${pCampaignFilter}))




SELECT
	DC.CASE_PRIORITY
	,CCLD.`YYYY-MM` 
	,COUNT(*) AS TOTAL_CASES
FROM F_CASE_MANAGEMENT FCM
INNER JOIN D_CASES DC
	ON FCM.CASE_TK = DC.CASE_TK
INNER JOIN D_DATE CCLD
	ON FCM.CASE_CLOSED_TK = CCLD.DATE_TK
GROUP BY 1,2


SELECT
	COUNT(IF(CCRD.`YYYY-MM` = 2019-03, FCM.CASE_TK, NULL)) AS CURRENT_NEW_LEADS
    ,COUNT(IF(CCRD.`YYYY-MM` = 2019-03 - 1, FCM.CASE_TK, NULL)) AS PREVIOUS_NEW_LEADS
FROM F_CASE_MANAGEMENT FCM
INNER JOIN D_CASES DC
	ON FCM.CASE_TK = DC.CASE_TK
INNER JOIN D_DATE CCRD
	ON FCM.CASE_CREATED_TK = CCRD.DATE_TK;

SELECT
	COUNT(IF(CASE_CLOSED_TK = 20180715, FCM.CASE_TK, NULL)) AS CURRENT_NEW_LEADS
    ,COUNT(IF(CASE_CLOSED_TK = 20180715 - 1, FCM.CASE_TK, NULL)) AS PREVIOUS_NEW_LEADS
FROM F_CASE_MANAGEMENT FCM;


	SELECT 
    COUNT(IF(DD.`YYYYMM` = ${pDateFilter}, FLM.LEAD_TK, NULL)) AS CURRENT_NEW_LEADS
    ,COUNT(IF(DD.`YYYYMM` = ${pDateFilter} - 1, FLM.LEAD_TK, NULL)) AS PREVIOUS_NEW_LEADS
FROM F_LEAD_MANAGEMENT FLM
INNER JOIN D_LEADS DL
	ON FLM.LEAD_TK = DL.LEAD_TK
INNER JOIN D_CAMPAIGNS AS DC 
	ON FLM.CAMPAIGN_TK = DC.CAMPAIGN_TK
INNER JOIN D_DATE DD
	ON FLM.LEAD_MODIFIED_TK = DD.DATE_TK
WHERE DL.LEAD_STATUS = 'New'
AND DD.`YYYYMM` IN (${pDateFilter},${pDateFilter} - 1)
AND (DC.CAMPAIGN_TYPE IN (${pCampaignTypeFilter}) OR 'All Campaign Types' IN (${pCampaignTypeFilter}))
AND (DC.CAMPAIGN_NAME IN (${pCampaignFilter}) OR 'All Campaigns' IN (${pCampaignFilter}));





SELECT
	DU.USER_NAME
	,COUNT(FCM.CASE_ID) AS TOTAL_CASES
	,AVG(IF(ISNULL(CCLD.`DD-MM-YYYY`), DATEDIFF(NOW(),CCRD.`DD-MM-YYYY`), DATEDIFF(CCLD.`DD-MM-YYYY`,CCRD.`DD-MM-YYYY`))) AS AVERAGE_CASE_AGE
FROM F_CASE_MANAGEMENT FCM
INNER JOIN D_CASES DC
	ON FCM.CASE_TK = DC.CASE_TK
INNER JOIN D_USERS DU
	ON FCM.ASSIGNED_USER_TK = DU.USER_TK
LEFT JOIN D_DATE CCRD
	ON FCM.CASE_CREATED_TK = CCRD.DATE_TK
LEFT JOIN D_DATE CCLD
	ON FCM.CASE_CLOSED_TK = CCLD.DATE_TK
GROUP BY 1

SELECT 
	DA.ACCOUNT_NAME
	,COUNT(FCM.CASE_ID)
FROM F_CASE_MANAGEMENT FCM
INNER JOIN D_ACCOUNTS DA
	ON FCM.ACCOUNT_TK = DA.ACCOUNT_TK
GROUP BY 1;

SELECT
	DU.USER_NAME
	,DA.ACCOUNT_NAME
	,DC.CASE_NAME
	,DC.CASE_TYPE
	,DC.CASE_STATUS
	,DC.CASE_STATE
	,DC.CASE_PRIORITY
	,CCRD.`DD-MM-YYYY` AS CASE_CREATED_DATE
	,CCLD.`DD-MM-YYYY` AS CASE_CLOSED_DATE
	,IF(ISNULL(CCLD.`DD-MM-YYYY`), DATEDIFF(NOW(),CCRD.`DD-MM-YYYY`), DATEDIFF(CCLD.`DD-MM-YYYY`,CCRD.`DD-MM-YYYY`)) AS CASE_AGE
FROM F_CASE_MANAGEMENT FCM
INNER JOIN D_CASES DC
	ON FCM.CASE_TK = DC.CASE_TK
INNER JOIN D_USERS DU
	ON FCM.ASSIGNED_USER_TK = DU.USER_TK
INNER JOIN D_ACCOUNTS DA
	ON FCM.ACCOUNT_TK = DA.ACCOUNT_TK
LEFT JOIN D_DATE CCRD
	ON FCM.CASE_CREATED_TK = CCRD.DATE_TK
LEFT JOIN D_DATE CCLD
	ON FCM.CASE_CLOSED_TK = CCLD.DATE_TK;